# Generated by Django 4.1.2 on 2022-10-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workarrangement",
            name="hours_per_week",
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(
                blank=True, default=None, max_length=200, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="team",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="api.team",
            ),
        ),
    ]
