# Generated by Django 4.1.2 on 2022-10-19 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_workarrangement_hours_per_week_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamleader",
            name="team",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_leader_team",
                to="api.team",
            ),
        ),
    ]
