# Generated by Django 4.1.2 on 2022-10-19 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_teamleader_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamemployee",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_employee_employee",
                to="api.employee",
            ),
        ),
    ]
