# Generated by Django 4.1.2 on 2022-10-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_teamemployee_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workarrangement",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_arrangements",
                to="api.employee",
            ),
        ),
    ]
