# Generated by Django 4.1.2 on 2022-10-20 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_workarrangement_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamemployee",
            name="team",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_employee_team",
                to="api.team",
            ),
        ),
        migrations.AlterField(
            model_name="teamleader",
            name="team",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_leader_team",
                to="api.team",
            ),
        ),
    ]
